sudo: false
language: python
cache: pip
matrix:
  global:
    - XDG_CACHE_HOME=$HOME/.cache
  include:
    - env: TOXENV=flake8
      python: 3.6
    - env: TOXENV=docs
      python: 3.6
    - env: TOXENV=py34-django1.11-drf3.6-jwt1.11
      python: 3.4
    - env: TOXENV=py34-django1.11-drf3.7-jwt1.11
      python: 3.4
    - env: TOXENV=py35-django1.11-drf3.6-jwt1.11
      python: 3.5
    - env: TOXENV=py35-django1.11-drf3.7-jwt1.11
      python: 3.5
    - env: TOXENV=py36-django1.11-drf3.6-jwt1.11
      python: 3.6
    - env: TOXENV=py36-django1.11-drf3.7-jwt1.11
      python: 3.6
    - env: TOXENV=py34-django2.0-drf3.7-jwt1.11
      python: 3.4
    - env: TOXENV=py35-django2.0-drf3.7-jwt1.11
      python: 3.5
    - env: TOXENV=py36-django2.0-drf3.7-jwt1.11
      python: 3.6

install:
  - travis_retry pip install tox
script:
  - tox
after_success:
  - |
    if [ "${TOXENV#py}" != "$TOXENV" ]; then
      pip install codecov
      coverage report -m || exit
      flags=${TOXENV//-/ }
      flags=${flags//./}
      codecov --required -X gcov --flags $flags || exit
    fi
notifications:
  email: false
